# Generated by Django 3.1.6 on 2021-06-12 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_branding_managers'),
        ('accounts', '0013_auto_20210611_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvitation',
            name='company',
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='branding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_invitations', to='restaurant.branding'),
        ),
    ]
