# Generated by Django 3.1.6 on 2021-05-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_branding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branding',
        ),
    ]
