# Generated by Django 3.1.6 on 2021-05-27 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0013_auto_20210521_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandinguser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_branding', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brandinguser',
            name='user_status',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'CUSTOMER'), ('MANAGER', 'MANAGER')], max_length=20, null=True),
        ),
    ]
