# Generated by Django 3.1.6 on 2021-05-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20210527_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='outlet',
            new_name='branding',
        ),
    ]
