# Generated by Django 3.1.6 on 2021-06-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_companybrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='branding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='restaurant.branding'),
        ),
    ]
