# Generated by Django 3.1.6 on 2021-06-04 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_orderitem_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='phone number')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_color', models.CharField(max_length=100)),
                ('text_color', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='company_brand_avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sub_domain', models.CharField(blank=True, max_length=180, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='branding_avatar')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('delivery_time_min', models.IntegerField(default=0)),
                ('delivery_time_max', models.IntegerField(default=0)),
                ('tax_rate', models.IntegerField(default=0)),
                ('tax_status', models.CharField(choices=[('INCLUSIVE', 'INCLUSIVE'), ('EXCLUSIVE', 'EXCLUSIVE')], default='EXCLUSIVE', max_length=20)),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('CASH', 'Cash')], default='CASH', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding_logo')),
                ('description', models.TextField()),
                ('tag_line', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='companybrand',
            name='company',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='address',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='delivery_time_max',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='delivery_time_min',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='description',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='email',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='outlets',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='tag_line',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='tax_status',
        ),
        migrations.DeleteModel(
            name='BrandingUser',
        ),
        migrations.DeleteModel(
            name='CompanyBrand',
        ),
        migrations.AddField(
            model_name='outlet',
            name='branding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding_outlet', to='restaurant.branding'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='delivery_area',
            field=models.ManyToManyField(related_name='delivery_outlet', to='restaurant.Location'),
        ),
        migrations.AddField(
            model_name='marketingbrand',
            name='branding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_brand', to='restaurant.branding'),
        ),
        migrations.AddField(
            model_name='brandingcustomer',
            name='branding',
            field=models.ManyToManyField(related_name='branding_customer', to='restaurant.Branding'),
        ),
    ]
