# Generated by Django 3.1.6 on 2021-06-04 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_brandingcustomer_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingbrand',
            name='branding',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_brand', to='restaurant.branding'),
        ),
    ]
