# Generated by Django 3.1.6 on 2021-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_auto_20210604_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='logo',
        ),
        migrations.AddField(
            model_name='branding',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding_logo'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='outlet_avatar'),
        ),
    ]
