# Generated by Django 3.1.6 on 2021-06-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_auto_20210604_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='sub_domain',
        ),
    ]
