# Generated by Django 3.1.6 on 2021-06-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_remove_outlet_sub_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingbrand',
            name='message',
        ),
        migrations.RemoveField(
            model_name='marketingbrand',
            name='title',
        ),
    ]
