# Generated by Django 3.1.6 on 2021-06-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_outlet_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingcustomer',
            name='branding',
            field=models.ManyToManyField(blank=True, null=True, related_name='branding_customer', to='restaurant.Branding'),
        ),
    ]
