# Generated by Django 3.1.6 on 2021-06-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_auto_20210609_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='apartment_address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='zip',
            new_name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default='a', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('BILLING', 'Billing'), ('SHIPPING', 'Shipping')], default='SHIPPING', max_length=50),
        ),
    ]
