# Generated by Django 3.1.6 on 2021-06-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_auto_20210612_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
