# Generated by Django 3.1.6 on 2021-06-12 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0031_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='brandings', to=settings.AUTH_USER_MODEL),
        ),
    ]
