# Generated by Django 3.1.6 on 2021-06-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_branding_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_VALUE', 'Fixed Value')], default='PERCENTAGE', max_length=20)),
                ('minimum_order_value', models.IntegerField(default=0)),
                ('maximum_discount', models.IntegerField(default=0)),
                ('number_of_uses', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
