# Generated by Django 3.1.6 on 2021-06-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_companydiscount_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydiscount',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companydiscount',
            name='type',
            field=models.CharField(choices=[('PERCENTAGE_VALUE', 'Percentage Value'), ('FIXED_VALUE', 'Fixed Value')], default='PERCENTAGE_VALUE', max_length=20),
        ),
    ]
