# Generated by Django 3.1.6 on 2021-06-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0036_auto_20210612_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydiscount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_discount', to='restaurant.company'),
        ),
    ]
