# Generated by Django 3.1.6 on 2021-06-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0037_auto_20210614_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingbrand',
            name='base_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketingbrand',
            name='text_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
