# Generated by Django 3.1.6 on 2021-06-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0038_auto_20210615_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='is_card_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outlet',
            name='is_cash_pay',
            field=models.BooleanField(default=False),
        ),
    ]
