# Generated by Django 3.1.6 on 2021-06-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0039_auto_20210615_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_payment',
            field=models.IntegerField(default=0),
        ),
    ]
