# Generated by Django 3.1.6 on 2021-06-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0040_order_total_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_payment',
            field=models.FloatField(default=0),
        ),
    ]
